services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy    # ← 重要：DBのヘルスチェックが通るまで待機
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: >
      sh -c "npx prisma migrate dev --name init && npx prisma db seed &&  npm run dev"
  db:
    image: postgres:15-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:                      # ← PostgreSQL用のヘルスチェック設定
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s              # ← 初期起動時の猶予期間

volumes:
  postgres_data:
